### ISSUE TITLE
package.json specifies package root as doc directory

### ISSUE THREAD

**Issue by evnm** [subtleGradient/Sheet.js#9]
I realize that this is nit-picky, but the package.json "doc" entry under directories is meant to point to a subdirectory containing markdown files. Breaking this standard may not mesh well with upcoming npm features.

**Comment by subtleGradient** [comment]
Well currently the only docs are the README markdown file. Is there some reason why that needs to be a separate directory?

**Comment by evnm** [comment]
The README is fine, but the intention for specifying a separate doc dir is to point to additional (or at least more comprehensive) documentation.

To reiterate, I'm speaking in terms of npm, and I realize that Sheet isn't Node-specific. Just wanted to mention it in light of a Node documentation system I'm working on. I apologize if this seemed preachy.

**Comment by subtleGradient** [comment]
So what should I do in the package.json file to support that if I only have the README?

**Comment by evnm** [comment]
Essentially nothing. You could remove the `"doc": ".",` line under `directories`, since there isn't a separate location for documentation.

**Comment by subtleGradient** [comment]
Fixed.
